**Ineuron Python Advance Assignment 1**

1. What makes NumPy.shape() different from NumPy.size()?

Answer: NumPy.shape() is an function which returns a tuple, the elements of the tuple give the lengths of the corresponding array dimensions. Wheeras, NumPy.size() function count the number of elements along a given axis.

In [1]:
import numpy as npy
arr1 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8]])
arr2 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8],
				[3, 6, 9, 12]])

# first element of tuple gives dimension of arrays second element of tuple gives number of element of each dimension
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)


(2, 4)
(3, 4)
8
12


2. In NumPy, describe the idea of broadcasting.

Answer: The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes. 
Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. NumPy is implemented in C. It does this without making needless copies of data and which leads to efficient algorithm implementations. There are cases where broadcasting is a bad idea because it leads to inefficient use of memory that slow down the computation.

Broadcasting two arrays together follow these rules:
 

- If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are compatible in a dimension if they have the same size in - - the dimension or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together iff they are compatible with all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.
  

In [5]:
import numpy as np
A = np.array([[11, 22, 33], [10, 20, 30]])
print(A)
b = 4
print(b)
C = A + b
print(C)

[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]



3. What makes Python better than other libraries for numerical computation?

Answer: In python there are lot of libraries which can be used to perform computation. Numpy is a fundamental numerical pakage in python. Numpy guarantees swift execution as it is accumulated with mathematical and numerical functions. Robust Python with its dynamic data structures, efficient implementation of multi-dimensional arrays and matrices, Numpy assures accurate calculations with matrices and arrays. We need to import Numpy into memory to perform numerical operations. There are other libraries also like pandas,scipy etc which makes working in python more easy.

4. How does NumPy deal with files?

Answer: NumPy introduces a simple file format for ndarray objects. This .npy file stores data, shape, dtype and other information required to reconstruct the ndarray in a disk file such that the array is correctly retrieved even if the file is on another machine with different architecture.

In [6]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('arrayfile',a)
b = np.load('arrayfile.npy') 
print( b) 

[1 2 3 4 5]


In [9]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b) 

[1. 2. 3. 4. 5.]



5. Mention the importance of NumPy.empty().

Answer: numpy.empty() is a function used to create an array without initializing the entries of given shape and type.
Just like numpy.zeros(), the numpy.empty() function doesn't set the array values to zero, and it is quite faster than the numpy.zeros(). This function requires the user to set all the values in the array manually and should be used with caution.

In [10]:
import numpy as np  
x = np.empty([3, 2])  
x  

array([[4.68951354e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])